### ISSUE TITLE
The game version is not compatible 

### ISSUE THREAD

**Issue by MSCgameplayer** [pawREP/ZHM5Randomizer#13] opened 2020-11-13 18:21 UTC
i installed the mod and started the game but the current version of the mod is not compatible with the game version

**Comment by baluwastaken** [comment] 2020-11-16 17:57
#12

**Comment by Heartran** [comment] 2020-11-18 15:36
> i installed the mod and started the game but the current version of the mod is not compatible with the game version

Same problem

**Comment by jolaquai** [comment] 2020-11-19 12:14
Vote to close this as it's a duplicate of #12 at @baluwastaken mentioned?

**Closed as completed** 2021-01-06 17:44 UTC
