### ISSUE TITLE
Not working with latest update

### ISSUE THREAD

**Issue by Britprogamer** [pawREP/ZHM5Randomizer#24] opened 2021-06-08 13:21 UTC
Im getting the signiture scanning failed error with the new game update. How long before an update to the randomizer as its one of the best mods ever and makes playing hitman much less boring and repetitive.??

**Comment by noneedinmagic** [comment] 2021-06-12 23:34
Duplicate of #22

**Closed as completed** 2021-06-12 23:57 UTC
Labels: duplicate
